# fly.toml app configuration file generated for sync-app on 2025-11-11T20:08:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sync-app'
primary_region = 'cdg'

[build]

[env]
PORT = '3000'
SCOPES = 'write_inventory,write_products'
SHOPIFY_API_KEY = 'f5cd656caba7027a223753d2be36fb8e'
SHOPIFY_APP_URL = 'https://sync-app.fly.dev/'

[processes]
app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
auto_extend_size_increment = '1GB'
auto_extend_size_limit = '10GB'
auto_extend_size_threshold = 80
destination = '/data'
source = 'data'

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 3000
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
